### ISSUE TITLE
Skeleton generation fails during c3d import with Full body Plug-in Gait VICON marker set

### ISSUE THREAD

**Issue by nigrape** [davidpagnon/Maya-Mocap#1]
Hi everyone, 

I'm currently struggling to convert motion capture data from c3d format (Nexus VICON) to trc format to generate a skeleton for animation purposes.

Indeed, the skeleton generation fails during c3d import of a recordign using a Full body Plug-in Gait VICON marker set.
When I tried a direct c3d import from the shelf with all skeletons (MPI not available from Maya GUI) I have the error message :
“maya_trc.py line 194: name 'skeleton_box' is not defined” 

Furthermore, I've noticed that a trc file has been generated anyway. However, once I try to import it from the trc shelf, whatever the skeleton I use, I have the error message:
“Error: KeyError: file C:\...\base.py line 3812: 'RHip_Z' (with BODY_25, BODY_25B, COCO, MPI) or CHipJ7 (with BODY_135) or CHipJ8 (with custom)

I don't what I'm missing or doing wrong... Can anyone help me with this conundrum ?

Thank you in advance for your help !

**Comment by davidpagnon** [comment]
Hi, I'm sorry I'm not maintaining this repo anymore, and I don't even have a Maya licence anymore...

However, if you don't mind switching, I recoded and improved the whole toolbox on Blender: https://github.com/davidpagnon/Pose2Sim_Blender

**Comment by nigrape** [comment]
Hi @davidpagnon,

Thank you for quick answer.
Thank you it worked also with Blender and Pos2Sim !
